// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbskieanaxiliuyevxuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJic2tpZWFuYXhpbGl1eWV2eHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODE2NTIsImV4cCI6MjA2MjQ1NzY1Mn0.NimpqiKCkvpqrc21Ov42RPHwQ4zntNpdlitGl56ryhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);